# Generated by Django 2.0.5 on 2018-05-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='acceptancecriteria',
            name='deliverable',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='work_package',
        ),
        migrations.RemoveField(
            model_name='workpackage',
            name='project',
        ),
        migrations.DeleteModel(
            name='AcceptanceCriteria',
        ),
        migrations.DeleteModel(
            name='Deliverable',
        ),
        migrations.DeleteModel(
            name='WorkPackage',
        ),
        migrations.AddField(
            model_name='acceptancecriterion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Item'),
        ),
    ]
