# Generated by Django 2.0.5 on 2018-05-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180522_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-folder']},
        ),
    ]
