# Generated by Django 2.0.5 on 2018-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180523_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='brief',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='description',
        ),
        migrations.AddField(
            model_name='folder',
            name='colour',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('indigo', 'Indifo'), ('orange', 'Orange'), ('red', 'Red'), ('violet', 'Violet'), ('yellow', 'Yellow')], default='green', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='deadline',
            field=models.DateField(default='2018-06-01'),
            preserve_default=False,
        ),
    ]
