# Generated by Django 2.0.5 on 2018-06-04 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_auto_20180523_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSupplierApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('IN', 'Invited')], max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='colour',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='itemsupplierapplication',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Item'),
        ),
        migrations.AddField(
            model_name='itemsupplierapplication',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
