# Generated by Django 2.0.5 on 2018-06-04 15:07

from django.db import migrations, models
import django.db.models.deletion
import forgeplatform.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180604_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=forgeplatform.projects.models.project_media_path)),
                ('time_submitted', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='acceptancecriterion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-folder', 'title']},
        ),
        migrations.AddField(
            model_name='itemwork',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Item'),
        ),
        migrations.AddField(
            model_name='criterionapproval',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.AcceptanceCriterion'),
        ),
        migrations.AddField(
            model_name='criterionapproval',
            name='item_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ItemWork'),
        ),
    ]
