# Generated by Django 2.0.5 on 2018-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180604_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptancecriterion',
            name='item',
        ),
        migrations.RemoveField(
            model_name='criterionapproval',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='criterionapproval',
            name='item_work',
        ),
        migrations.AddField(
            model_name='item',
            name='dimensions',
            field=models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('CS', 'Custom')], default='A4', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='file_format',
            field=models.CharField(choices=[('BMP', 'Windows BMP image (*.bmp)'), ('GIF', 'GIF image (*.gif)'), ('JPEG', 'JPEG image (*.jpeg, *.jpg)'), ('PDF', 'Portable Document Format (*.pdf)'), ('PSD', 'Photoshop Document (*.psd)'), ('TIFF', 'TIFF image (*.tiff, *.tif)')], default='JPEG', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='kick_off',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='payment',
            field=models.CharField(choices=[('FI', 'FIAT'), ('EQ', 'Equity'), ('PB', 'Pro Bono'), ('RY', 'Royalties')], default='FI', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='resolution',
            field=models.CharField(choices=[('LO', 'Low'), ('MD', 'Medium'), ('HI', 'High')], default='HI', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='supplier_level',
            field=models.CharField(choices=[('JN', 'Junior'), ('ML', 'Mid Level'), ('SN', 'Senior')], default='JN', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='supplier_role',
            field=models.CharField(choices=[('DS', 'Designer'), ('DD', 'Digital Designer'), ('UX', 'UX/UI Designer'), ('CM', 'Colour Material Designer'), ('DE', 'Design Engineer')], default='DS', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemwork',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemwork',
            name='dimensions_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemwork',
            name='file_format_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemwork',
            name='resolution_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AcceptanceCriterion',
        ),
        migrations.DeleteModel(
            name='CriterionApproval',
        ),
    ]
