# Generated by Django 2.0.5 on 2018-06-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180606_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='payment',
            new_name='payment_method',
        ),
        migrations.AddField(
            model_name='item',
            name='amends',
            field=models.IntegerField(default=3),
        ),
    ]
