# Generated by Django 2.0.5 on 2018-06-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180606_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEthTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_code', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Item')),
            ],
        ),
    ]
