# Generated by Django 2.0.5 on 2018-06-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180607_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsupplierapplication',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
