# Generated by Django 2.0.5 on 2018-06-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_itemsupplierapplication_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsupplierapplication',
            old_name='cancelled',
            new_name='declined',
        ),
    ]
