# Generated by Django 2.0.5 on 2018-06-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180611_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwork',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='itemwork',
            name='dimensions_approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='itemwork',
            name='file_format_approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='itemwork',
            name='resolution_approved',
            field=models.NullBooleanField(),
        ),
    ]
