# Generated by Django 2.0.5 on 2018-06-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180612_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemwork',
            options={'ordering': ['time_submitted']},
        ),
    ]
