# Generated by Django 2.0.5 on 2018-06-20 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0017_auto_20180613_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileItemEthAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=42)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='curated',
            field=models.BooleanField(default=False),
        ),
    ]
