# Generated by Django 2.0.5 on 2018-06-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20180620_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemethtx',
            name='activity',
            field=models.CharField(choices=[('AD', 'Add item'), ('SS', 'Set supplier'), ('DE', 'Add design'), ('AP', 'Approve item')], default='AD', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemwork',
            name='picture_hash',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
