# Generated by Django 2.0.5 on 2018-06-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20180623_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemethtx',
            name='item_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ItemWork'),
        ),
    ]
