# Generated by Django 2.0.5 on 2018-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_itemethtx_item_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsupplierapplication',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
