# Generated by Django 2.0.5 on 2018-06-29 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0022_itemsupplierapplication_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profileitemethadd',
            unique_together={('profile', 'item')},
        ),
    ]
