# Generated by Django 2.0.5 on 2018-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20180629_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approval_seen_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='approval_seen_by_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
