# Generated by Django 2.0.5 on 2018-07-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20180706_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR - Euro'), ('GBP', 'GBP - Great British Pound'), ('USD', 'USD - US Dollar'), ('YEN', 'YEN - Japanese Yen')], max_length=3),
        ),
    ]
