# Generated by Django 2.0.5 on 2018-07-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20180706_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_access', 'Can access project pages'),)},
        ),
    ]
