from django.urls import path

from .views import (
    ProjectList,
    ProjectView,
    ProjectCreate,
    ProjectUpdate,
    ProjectDelete,
    FolderCreate,
    FolderUpdate,
    FolderDelete,
    ItemCreate,
    ItemUpdate,
    ItemDelete,
    ProjectEditView,
    ProjectOwnerList,
    ItemInviteSupplierList,
    ItemInviteSupplierConfirm,
    ItemInviteSupplierCancel,
    ItemInviteAccept,
    ItemInviteDecline,
    ItemSupplierApply,
    ItemApplicationAccept,
    ItemSupplierCancelApp,
    ItemSupplierManagement,
    ItemWorkSubmit,
    ItemWorkCancel,
    ItemWorkFeedback,
    add_item_eth_tx,
    item_approval_seen_by_supplier,
    item_approval_seen_by_owner,
    ItemWorkEthOwnership,
) 


urlpatterns = [
    path('project_list/', ProjectList.as_view(), name="project_list"),
    path('project_owner_list/', ProjectOwnerList.as_view(), name="project_owner_list"),
    path('project_view/<int:pk>', ProjectView.as_view(), name='project_view'),
    path('project_create/', ProjectCreate.as_view(), name='project_create'),
    path('project_update/<int:pk>', ProjectUpdate.as_view(), name='project_update'),
    path('project_delete/<int:pk>', ProjectDelete.as_view(), name='project_delete'),
    path('folder_create/<int:project_pk>', FolderCreate.as_view(), name='folder_create'),
    path('folder_update/<int:pk>', FolderUpdate.as_view(), name='folder_update'),
    path('folder_delete/<int:pk>', FolderDelete.as_view(), name='folder_delete'),
    path('item_create/<int:project_pk>', ItemCreate.as_view(), name='item_create'),
    path('item_update/<int:pk>', ItemUpdate.as_view(), name='item_update'),
    path('item_delete/<int:pk>', ItemDelete.as_view(), name='item_delete'),
    path('project_edit_view/<int:pk>', ProjectEditView.as_view(), name='project_edit_view'),
    path('item_invite_supplier_list/<int:item_pk>', ItemInviteSupplierList.as_view(), name='item_invite_supplier_list'),
    path('item_invite_supplier_confirm/<int:item_pk>/<int:profile_pk>', ItemInviteSupplierConfirm.as_view(), name='item_invite_supplier_confirm'),
    path('item_invite_supplier_cancel/<int:pk>', ItemInviteSupplierCancel.as_view(), name='item_invite_supplier_cancel'),
    path('item_invite_accept/<int:pk>', ItemInviteAccept.as_view(), name='item_invite_accept'),
    path('item_application_accept/<int:pk>/<int:application_pk>', ItemApplicationAccept.as_view(), name='item_application_accept'),
    path('item_invite_decline/<int:pk>', ItemInviteDecline.as_view(), name='item_invite_decline'),
    path('item_supplier_apply/<int:pk>', ItemSupplierApply.as_view(), name='item_supplier_apply'),
    path('item_supplier_cancel_application/<int:pk>', ItemSupplierCancelApp.as_view(), name='item_supplier_cancel_app'),
    path('item_supplier_management/<int:pk>', ItemSupplierManagement.as_view(), name='item_supplier_management'),
    path('item_work_submit/<int:item_pk>', ItemWorkSubmit.as_view(), name='item_work_submit'),
    path('item_work_cancel/<int:pk>', ItemWorkCancel.as_view(), name='item_work_cancel'),
    path('item_work_feedback/<int:pk>', ItemWorkFeedback.as_view(), name='item_work_feedback'),
    path('item_work_eth_ownership/<int:pk>', ItemWorkEthOwnership.as_view(), name='item_work_eth_ownership'),
    path(
        'add_item_eth_tx',
        add_item_eth_tx,
        name='add_item_eth_tx',
    ),
    path(
        'item_approval_seen_by_supplier/<int:pk>',
        item_approval_seen_by_supplier,
        name='item_approval_seen_by_supplier',
    ),
    path(
        'item_approval_seen_by_owner/<int:pk>',
        item_approval_seen_by_owner,
        name='item_approval_seen_by_owner',
    ),
]